# Generated by Django 4.1.6 on 2023-02-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True, default="Online", max_length=100, null=True
            ),
        ),
    ]
